# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.8
_src_path: ../../ModernAppTemplate/backend
author_email: pvginkel@gmail.com
author_name: Pieter van Ginkel
backend_port: 3101
database_name: iotsupport
frontend_port: 3100
image_name: registry:5000/iotsupport-app
project_description: Flask backend for managing ESP32 IoT device configurations
project_name: iot-support
repo_url: https://github.com/pvginkel/IoTSupport.git
s3_bucket_name: iot-support-attachments
sse_gateway_port: 3102
testing_port_offset: 10
use_database: true
use_oidc: true
use_s3: true
use_sse: true
