#!/bin/sh
# Generate the .env / .env.test files a fresh clone needs.
#
# Both files are gitignored, so a fresh checkout has neither. Everything here
# is a non-secret local default pointing at the environment's sidecars; only
# the values that differ from the defaults in app/config.py are listed.
#
# Existing files are left alone, so local edits survive re-running setup.

set -e

BACKEND_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# The MinIO sidecar's root credentials. The code defaults (admin/password) do
# not match it; these are the same values CI uses.
S3_ENDPOINT_URL=http://localhost:9000
S3_ACCESS_KEY_ID=minioadmin
S3_SECRET_ACCESS_KEY=minioadmin

# The homelab dev Keycloak. Only the non-secret coordinates live here; the
# IoTSupport-specific admin client id and secret arrive as environment
# variables from the secret catalog (and env beats .env in pydantic-settings).
# Creating a device creates a Keycloak client, so the Playwright suite needs
# a real Keycloak — it is not optional.
KEYCLOAK_BASE_URL=http://keycloak-dev
KEYCLOAK_REALM=homelab-dev

if [ -f "$BACKEND_DIR/.env" ]; then
    echo ".env already exists, leaving it alone"
else
    cat > "$BACKEND_DIR/.env" <<EOF
# Generated by scripts/generate-dev-env.sh. Edit freely — setup will not
# overwrite an existing file.
S3_ENDPOINT_URL=$S3_ENDPOINT_URL
S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
S3_BUCKET_NAME=iot-support-attachments

# Device log viewer reads from the OpenSearch sidecar; defaults to unset,
# which disables the feature.
ELASTICSEARCH_URL=http://localhost:9200

KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL
KEYCLOAK_REALM=$KEYCLOAK_REALM
OIDC_TOKEN_URL=$KEYCLOAK_BASE_URL/realms/$KEYCLOAK_REALM/protocol/openid-connect/token
EOF
    echo "Wrote .env"
fi

# pytest_configure in tests/conftest_infrastructure.py exits unless
# S3_ENDPOINT_URL is present in the environment, and .env.test is where it
# looks for it.
if [ -f "$BACKEND_DIR/.env.test" ]; then
    echo ".env.test already exists, leaving it alone"
else
    cat > "$BACKEND_DIR/.env.test" <<EOF
# Generated by scripts/generate-dev-env.sh. Edit freely — setup will not
# overwrite an existing file.
S3_ENDPOINT_URL=$S3_ENDPOINT_URL
S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
S3_BUCKET_NAME=iot-support-test
EOF
    echo "Wrote .env.test"
fi
